version: '3.8'

services:
  flask-app:
    build: .
    command: python src/app.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file: 
      - .env
    ports: 
      - "5432:5432"
    expose: 
      - "5432"  
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pacientesALyP
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql

  


volumes:
  postgres_data:
